# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - gem update xcpretty cocoapods
  - pod update
script:
  - xcodebuild -workspace CBRCloudKitConnection.xcworkspace -scheme CBRCloudKitConnection test -sdk iphonesimulator -configuration Release | xcpretty -c; exit ${PIPESTATUS[0]}
